name: Build wheel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Download model from VOSK website
      run: |
        wget https://alphacephei.com/vosk/models/vosk-model-small-ja-0.22.zip
        unzip -d voskhttp/models vosk-model-small-ja-0.22.zip
    - name: Build project
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        python -m build --wheel
    - name: Archive resulting wheel
      uses: actions/upload-artifact@v4
      with:
        name: voskhttp-wheel
        path: dist/*.whl
